### ISSUE TITLE
Вопросы к управлению

### ISSUE THREAD

**Issue by SID37** [Daria-Romanko/Forgotten-World#44]
Я не очень понял, по какому принципу что-то делается на E, а что-то кликом мышки. А вообще, и действие, и проматывание диалога, и выход из миниигр можно повесить на одну кнопку (например E), потому что они не происходят одновременно

**Comment by xdariko** [comment]
@SID37 Исправили управление, теперь оно действительно стало удобнее. Взаимодействие, открытие и закрытие миниигр и разных панелек теперь делается на кнопку Е. Только проматывание диалога оставили на пробел, для большинства из нас это привычнее.
